/*
	http://en.wikipedia.org/wiki/Extreme_points_of_the_United_States#Westernmost
	Lower 48 Bounding Box
	top = 49.3457868 # north lat
	left = -124.7844079 # west long
	right = -66.9513812 # east long
	bottom =  24.7433195 # south lat
*/
DROP TABLE IF EXISTS Addresses;

CREATE TABLE Addresses (
  Id INT NOT NULL AUTO_INCREMENT,
  Number VARCHAR(50),
  Street VARCHAR(100),
  City VARCHAR(100),
  Region VARCHAR(2),
  Postcode VARCHAR(10),
  Unit VARCHAR(50),
  Floor VARCHAR(50),
  Building VARCHAR(50),
  Lat DECIMAL(10, 8) NOT NULL,
  Lat_2 SMALLINT NOT NULL,
  Lon DECIMAL(11, 8) NOT NULL,
  Lon_2 SMALLINT NOT NULL,
  INDEX(Id),
  INDEX(Number),
  INDEX(Street(3)),
  PRIMARY KEY (Lon_2, Lat_2, Id)
)
PARTITION BY RANGE(Lat_2) (
	PARTITION p0 VALUES LESS THAN (2500),
	PARTITION p1 VALUES LESS THAN (2600),
	PARTITION p2 VALUES LESS THAN (2700),
	PARTITION p3 VALUES LESS THAN (2800),
	PARTITION p4 VALUES LESS THAN (2900),
	PARTITION p5 VALUES LESS THAN (3000),
	PARTITION p6 VALUES LESS THAN (3100),
	PARTITION p7 VALUES LESS THAN (3200),
	PARTITION p8 VALUES LESS THAN (3300),
	PARTITION p9 VALUES LESS THAN (3400),
	PARTITION p10 VALUES LESS THAN (3500),
	PARTITION p11 VALUES LESS THAN (3600),
	PARTITION p12 VALUES LESS THAN (3700),
	PARTITION p13 VALUES LESS THAN (3800),
	PARTITION p14 VALUES LESS THAN (3900),
	PARTITION p15 VALUES LESS THAN (4000),
	PARTITION p16 VALUES LESS THAN (4100),
	PARTITION p17 VALUES LESS THAN (4200),
	PARTITION p18 VALUES LESS THAN (4300),
	PARTITION p19 VALUES LESS THAN (4400),
	PARTITION p20 VALUES LESS THAN (4500),
	PARTITION p21 VALUES LESS THAN (4600),
	PARTITION p22 VALUES LESS THAN (4700),
	PARTITION p23 VALUES LESS THAN (4800),
	PARTITION p24 VALUES LESS THAN (4900),
	PARTITION p25 VALUES LESS THAN (MAXVALUE)
);

LOAD DATA LOCAL INFILE '@CsvFile'
INTO TABLE Addresses
FIELDS TERMINATED BY '|'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(
  @Id,
  @Number,
  @Street,
  @City,
  @Region,
  @Postcode,
  @Unit,
  @Floor,
  @Building,
  @Lat,
  @Lon
)
SET
  Id = @Id,
  Number = @Number,
  Street = @Street,
  City = @City,
  Postcode = @Postcode,
  Region = @Region,
  Unit = @Unit,
  Floor = @Floor,
  Building = @Building,
  Lat = @Lat,
  Lat_2 = ROUND(@Lat * 100),
  Lon = @Lon,
  Lon_2 = ROUND(@Lon * 100)
;
