version: "3"
services:
  mysql:
    image: mysql
    command:
      --default-authentication-plugin=mysql_native_password
      --local-infile
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    volumes:
      - esdata1:/usr/share/mysql/data
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    container_name: es
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - esdata1:/usr/share/elasticsearch/data
  api:
    image: eheineking/autocomplete-address-api
    command: npm start
    container_name: autocomplete-address-api
    depends_on:
      - es
    ports:
      - 3001:3001
  app:
    build: ./app
    command: npm start
    depends_on:
      - api
    ports:
      - 3000:3000
volumes:
  esdata1:
    driver: local
